---
# export VAULT_NAMESPACE="monaco"
# https://terryhowe.github.io/ansible-modules-hashivault/modules/list_of_hashivault_modules.html
- name: Validation playbook for Vault secret retrieving
  hosts: all
  user: gauth
  tasks:
    - name: Retrieving secret
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=kv/data/magellan auth_method=ldap username=admin password=password24 validate_certs=no url=https://v1.starfly.fr:8200')}}"



...
