---
# export VAULT_NAMESPACE="monaco"
# https://terryhowe.github.io/ansible-modules-hashivault/modules/list_of_hashivault_modules.html

# /!\ The request must be sent to the primary vault node or through a LB as hashi_vault does not handle the session with another node
- name: Validation playbook for Vault secret retrieving
  hosts: all
  user: gauth
  tasks:
    - name: Retrieving secret
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=kv/data/magellan:name auth_method=userpass username=admin password=mypass validate_certs=no url=https://v2.starfly.fr:8200')}}"



...
