---
# export VAULT_NAMESPACE="monaco"
# https://terryhowe.github.io/ansible-modules-hashivault/modules/list_of_hashivault_modules.html
# https://docs.ansible.com/ansible/latest/plugins/lookup/hashi_vault.html

# /!\ The request must be sent to the primary vault node or through a LB as hashi_vault does not handle the session with another node
- name: Validation playbook for Vault secret retrieving
  hosts: all
  tasks:
    # If you wanna had a namespace specification add the parameter "namespace=teama/admins"
    - name: Retrieving secret using userpass
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=kv/data/magellan auth_method=userpass username=admin password='+ mypass +' validate_certs=no url='+ url)}}"

    - name: Retrieving secret using approle
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=kv/data/magellan auth_method=approle role_id='+ role_id +' secret_id='+ secret_id +' validate_certs=no url='+ url)}}"


...
