---
# export VAULT_NAMESPACE="monaco"
# https://terryhowe.github.io/ansible-modules-hashivault/modules/list_of_hashivault_modules.html
- name: Validation playbook for Vault secret retrieving
  hosts: all
  user: gauth
  tasks:
  	- name: Retrieving secret
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/hello:value auth_method=userpass mount_point=kv username=myuser password=mypas url=http://myvault:8200')}}"

- name: Vault that requires authentication via username and password
  debug:
      msg: "{{ lookup('hashi_vault', 'secret=secret/hello:value auth_method=userpass username=myuser password=mypas url=http://myvault:8200')}}"





...